export const ApiConstants = {
  authBaseUrl: 'https://auth-serv.tekstagearea.com/v1/api/',
  baseUrl: 'https://zillow-backend.tekstagearea.com/api/v1/',
  s3Endpoint: 'https://block_tix-app.s3.us-east-1.amazonaws.com/',
  uploadsFolder: 'uploads/',
  adsFolder: 'ads/',
  authPath: 'auth/',
  commonHeaderValue: 'qJCcwiJ62M2wuUjKZPxY',
  timeoutMs: 50000,
  otpLength: 6,
  paginationLimit: 10,
  maxImageSizeMb: 3,
} as const;

export const ApiUrls = {
  login: `${ApiConstants.authBaseUrl}${ApiConstants.authPath}login`,
  signup: `${ApiConstants.authBaseUrl}${ApiConstants.authPath}signup`,
  socialAuth: `${ApiConstants.authBaseUrl}${ApiConstants.authPath}social-auth`,
  resendVerificationOtp: `${ApiConstants.authBaseUrl}${ApiConstants.authPath}resend-verification-otp`,
  verifyAccount: `${ApiConstants.authBaseUrl}${ApiConstants.authPath}verify-account`,
  forgotPassword: `${ApiConstants.authBaseUrl}${ApiConstants.authPath}forgot-password`,
  resendOtp: `${ApiConstants.authBaseUrl}${ApiConstants.authPath}resend-otp`,
  verifyOtp: `${ApiConstants.authBaseUrl}${ApiConstants.authPath}verify-otp`,
  resetPassword: `${ApiConstants.authBaseUrl}${ApiConstants.authPath}reset-password`,
  changePassword: `${ApiConstants.authBaseUrl}${ApiConstants.authPath}change-password`,
  updateProfile: `${ApiConstants.authBaseUrl}${ApiConstants.authPath}update-profile`,
  getProfile: `${ApiConstants.authBaseUrl}${ApiConstants.authPath}get-profile`,
  logout: `${ApiConstants.authBaseUrl}${ApiConstants.authPath}logout`,
  userList: `${ApiConstants.authBaseUrl}${ApiConstants.authPath}user-list`,
  deleteUser: `${ApiConstants.authBaseUrl}${ApiConstants.authPath}delete-user`,

  // Core app endpoints
  reportTypes: `${ApiConstants.baseUrl}report-types`,
  preferences: `${ApiConstants.baseUrl}preference`,
  properties: `${ApiConstants.baseUrl}property`,
  singleProperty: (id: string) => `${ApiConstants.baseUrl}property/mls/${id}`,
  saveProperty: `${ApiConstants.baseUrl}preference/save-property`,
  removeSavedProperty: `${ApiConstants.baseUrl}preference/remove-saved-property`,
  shareProperty: `${ApiConstants.baseUrl}property/share`,
  updatePreferences: (id: string) => `${ApiConstants.baseUrl}preference/${id}`,
  resetPreferences: (id: string) => `${ApiConstants.baseUrl}preference/reset/${id}`,
  addHideList: `${ApiConstants.baseUrl}preference/add-property-hidelist`,
  addReport: `${ApiConstants.baseUrl}report/add-report`,
  contactUs: `${ApiConstants.baseUrl}contact-us/add-contact-us`,
  savedSearches: `${ApiConstants.baseUrl}saved-search`,
  addSavedSearch: `${ApiConstants.baseUrl}saved-search/add-saved-search`,
  deleteAllSearches: `${ApiConstants.baseUrl}saved-search/all`,
  deleteSearch: (id: string) => `${ApiConstants.baseUrl}saved-search/${id}`,
  rotatedAds: `${ApiConstants.baseUrl}ads/rotated`,
  ads: `${ApiConstants.baseUrl}ads`,
  createAd: `${ApiConstants.baseUrl}ads/add-iad`,
  terms: `${ApiConstants.baseUrl}pages/terms-and-condition`,
  privacy: `${ApiConstants.baseUrl}pages/privacy-policy`,
  aboutUs: `${ApiConstants.baseUrl}pages/about-us`,
  faqs: `${ApiConstants.baseUrl}faqs`,
  deleteOptions: `${ApiConstants.baseUrl}delete-options`,
  notifications: `${ApiConstants.baseUrl}notification/`,
  markNotificationSeen: (id: string) => `${ApiConstants.baseUrl}notification/${id}`,
  packages: `${ApiConstants.baseUrl}package`,
  cards: `${ApiConstants.baseUrl}card`,
  myCards: `${ApiConstants.baseUrl}card/my-cards`,
  addCard: `${ApiConstants.baseUrl}card/add-card`,
  deleteCard: (id: string) => `${ApiConstants.baseUrl}card/${id}`,
  myProperties: `${ApiConstants.baseUrl}property/my-properties`,
  addProperty: `${ApiConstants.baseUrl}property/add-property`,
};
